#
# Copyright 2020 Nasim Hamrah Industries
#

##################################################
# AXI Sources
##################################################
AXI_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/axi/, \
axi_parity_error_detection.v \
axi_uart_rx.v \
axi_uart_trx_tb.v \
axi_uart_tx.v \
axis_ask_uart_tx_wrapper.v \
axis_uart_rx_wrapper.v \
axis_uart_tx_wrapper.v \
))
